# -*- coding: utf-8 -*-
"""email_spam_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SIuI4W2EU2nf9IcviRPDAanktNAusswr
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import re
import joblib

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import pandas as pd
import os

csv_file = [f for f in os.listdir() if f.endswith(".csv")][0]

encodings = [
    'utf-8',
    'utf-8-sig',
    'latin1',
    'ISO-8859-1',
    'cp1252'
]

df = None

for enc in encodings:
    try:
        df = pd.read_csv(csv_file, encoding=enc)
        print(f"Dataset loaded successfully using {enc} encoding")
        break
    except:
        continue

if df is None:
    raise Exception("Unable to read CSV file")

print("Dataset Shape:", df.shape)
print(df.head())

object_columns = df.select_dtypes(include=['object']).columns

text_col = None
max_length = 0

for col in object_columns:

    avg_length = df[col].astype(str).str.len().mean()

    if avg_length > max_length:
        max_length = avg_length
        text_col = col

print("Detected Text Column:", text_col)
label_col = None

for col in df.columns:

    if col == text_col:
        continue

    unique_count = df[col].nunique()

    if unique_count <= 20:
        label_col = col
        break

if label_col is None:
    raise Exception("Label column not found")

print("Detected Label Column:", label_col)

df = df[[text_col, label_col]]

df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z0-9 ]', ' ', text)
    return text

df[text_col] = df[text_col].apply(clean_text)

df[label_col] = df[label_col].astype(str).str.lower()

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df[label_col] = encoder.fit_transform(
    df[label_col].astype(str)
)

print("Classes Found:")
print(encoder.classes_)

print("Cleaned Dataset Shape:", df.shape)

X = df[text_col]
y = df[label_col]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

print("Training Samples:", len(X_train))
print("Testing Samples :", len(X_test))

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

print(X_train_vec.shape)

models = {
    "Naive Bayes": MultinomialNB(),
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "SVM": LinearSVC()
}

best_model = None
best_f1 = 0

results = []

for name, model in models.items():

    model.fit(X_train_vec, y_train)

    pred = model.predict(X_test_vec)

    accuracy = accuracy_score(y_test, pred)
    precision = precision_score(y_test, pred)
    recall = recall_score(y_test, pred)
    f1 = f1_score(y_test, pred)

    results.append([
        name,
        accuracy,
        precision,
        recall,
        f1
    ])

    print("\n", "="*50)
    print(name)
    print("="*50)

    print("Accuracy :", round(accuracy*100,2),"%")
    print("Precision:", round(precision*100,2),"%")
    print("Recall   :", round(recall*100,2),"%")
    print("F1 Score :", round(f1*100,2),"%")

    if f1 > best_f1:
        best_f1 = f1
        best_model = model

print("\nBest Model Selected Successfully")

comparison = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]
)

comparison

joblib.dump(best_model, "best_model.pkl")
joblib.dump(vectorizer, "tfidf.pkl")

print("Best Model Saved")
print(best_model)

email = input("Enter Email:\n")

vector = vectorizer.transform([email])

prediction = best_model.predict(vector)[0]

if prediction == 1:
    print("SPAM")
else:
    print("HAM")